plugins {
    id 'application'
}

group = 'tndmadman'
version = '0.6.0-p2-publish-audit'

repositories {
    mavenCentral()
}

sourceSets.main.java.srcDirs = ['src']

application {
    mainClass = 'redditTxtToImg.P2Entrypoint'
}

jar {
    archiveBaseName = 'ThreadGens'
    manifest {
        attributes 'Main-Class': 'redditTxtToImg.P2Entrypoint'
    }
}