plugins {
    id 'application'
}

group = 'tndmadman'
version = '0.4.0-x-platform'

repositories {
    mavenCentral()
}

sourceSets.main.java.srcDirs = ['src']

application {
    mainClass = 'redditTxtToImg.CheckedRunner'
}

jar {
    archiveBaseName = 'ThreadGens'
    manifest {
        attributes 'Main-Class': 'redditTxtToImg.CheckedRunner'
    }
}
